version: '3.8'
services:
  # For terminal access
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces
    command: sleep infinity
    network_mode: host
    environment:
      MONGO_URL: mongodb://localhost:27017
      MINIO_ENDPOINT: localhost:9000
      MINIO_ACCESS_KEY: W5DZH4uYAgsR08RyfkxM
      MINIO_SECRET_KEY: 20IeT7XsWEV3cNV93MzoP08w5CPjYuZsuvcT6lVf
    # ports:
    #   - target: 8082
    #   - published: 127.0.0.1:5000
    # networks:
    #   - my_network
    # minio:
    #   image: minio/minio
    #   container_name: minio
    #   ports:
    #     - "9000:9000"
    #   environment: &minio_env
    #     MINIO_ROOT_USER: minio
    #     MINIO_ROOT_PASSWORD: minio123
    #   volumes:
    #     - ../minio_store:/data
    #   network_mode: host
    #   command: server /data --console-address ":9001"
    # mongodb:
    #   image: mongo:7.0
    #   ports:
    #     - '27017:27017'
    #   volumes:
    #     - ../db:/data/db
    #   network_mode: host

    # mongo-express:
    #   image: mongo-express
    #   container_name: mongo-express
    #   ports:
    #     - "8081:8081"
    #   environment:
    #     - ME_CONFIG_MONGODB_URL=mongodb://localhost:27017
    #     # - ME_CONFIG_MONGODB_SERVER=mongodb
    #     # - ME_CONFIG_MONGODB_PORT=27017
    #   network_mode: host
